config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show] do
      collection do
          get '/search' => 'items#search'
      end
    end
    resources :item_genres, only: [:show]

    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :destinations, only: [:index, :edit, :create, :update, :destroy]

    get 'customers' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/information' => 'customers#update'
    patch 'customers/quit'

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :item_genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]do
      member do
        get 'order_index'
      end
    end
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :searchs, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :destinations

  validates :last_name,       presence: true
  validates :last_name_kana,  presence: true
  validates :first_name,      presence: true
  validates :first_name_kana, presence: true
  validates :email,           presence: true, uniqueness: true
  validates :postal_code,     presence: true, format: { with: /\A\d{7}\z/, allow_blank: true}
  validates :address,         presence: true
  validates :phone_number,    presence: true, format: { with: /\A0\d{9,10}\z/, allow_blank: true}

  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["last_name","first_name", "phone_number"]
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.page(params[:page]).per(10)
    @q = Item.ransack(params[:q])
  end

  def order_index
    @customer = Customer.find(params[:id])
    @orders = Order.where(customer_id: @customer.id).order(created_at: :desc).page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "情報の更新に成功しました。"
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :address, :postal_code, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h2><%= @customer.full_name %>さんの会員情報編集</h2>
<%= form_with model: @customer, url: admin_customer_path do |f| %>
  <table class="table table-borderless mt-3 mb-5">
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= f.text_field :last_name, class: "form-control" %></td>
      <td><%= f.text_field :first_name, class: "form-control" %></td>
      <td></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= f.text_field :last_name_kana, class: "form-control" %></td>
      <td><%= f.text_field :first_name_kana, class: "form-control" %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= f.text_field :postal_code, class: "form-control" %></td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>住所</td>
      <td colspan="2"><%= f.text_field :address, class: "form-control" %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= f.text_field :phone_number, class: "form-control" %></td>
      <td></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= f.email_field :email, class: "form-control" %></td>
      <td></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "退会" %>
        <%= f.radio_button :is_deleted, true %>
      </td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
    </tr>
  </table>
<% end %>

app/views/admin/customers/index.html.erb
<div class="row d-inline">
  <div class="offset-2 pl-3">
    <h5 class="bg-light col-2 text-center px-0">会員一覧</h5>
  </div>
  <div class="col-md-8 mx-auto">
    <table class="table table-hover border-bottom">
      <thead class="bg-light table-sm text-center">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr class="text-center">
            <td class="align-middle"><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.full_name %>
              <% end %>
            </td>
            <td class="align-middle"><%= customer.email %></td>
            <td class="align-middle">
              <% if customer.is_deleted == false %>
                <p class="text-success font-weight-bold align-middle mb-0">有効</p>
              <% else %>
                <p class="text-secondary font-weight-bold align-middle mb-0">退会</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row">
      <div class="mx-auto mb-5">
        <%= paginate @customers, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/order_index.html.erb
<div class="row d-inline">
  <div class="offset-2 pl-3">
    <h5 class="bg-light col-4 text-center px-0"><%= @customer.full_name %>さんの注文履歴一覧</h3>
  </div>
  <div class="col-md-8 mx-auto">
    <table class="table table-hover border-bottom">
      <thead class="bg-light">
        <tr class="text-center">
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr class="text-center">
              <!--購入日時-->
            <td>
              <%= link_to admin_order_path(order) do %>
                <%= l order.created_at,format: :time %>
              <% end %>
            </td>
              <!--注文個数-->
            <td class="align-middle"><%= order.order_items.sum(:count) %></td>
              <!--注文ステータス-->
            <td class="align-middle"><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row">
      <div class="mx-auto mb-5">
        <%= paginate @orders, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h2><%= @customer.full_name %>さんの会員詳細</h2>
<table class="table table-borderless mt-3 mb-5">
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
    <td></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= @customer.last_name %>  <%=@customer.first_name %></td>
    <td></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td><%= @customer.last_name_kana %>  <%=@customer.first_name_kana %></td>
    <td></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= @customer.postal_code %></td>
    <td></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= @customer.address %></td>
    <td></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= @customer.phone_number %></td>
    <td></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= @customer.email %></td>
    <td></td>
  </tr>
  <tr>
    <td>会員ステータス</td>
    <td>
      <% if @customer.is_deleted == false %>
        <p class="text-success font-weight-bold">有効</p>
      <% else %>
        <p class="text-secondary font-weight-bold"></p>退会</p>
      <% end %>
    </td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success btn-md" %></td>
    <td><%= link_to "注文履歴一覧を見る", order_index_admin_customer_path(@customer.id), class: "btn btn-primary btn-md" %></td>
  </tr>
</table>