config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show] do
      collection do
          get '/search' => 'items#search'
      end
    end
    resources :item_genres, only: [:show]

    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :destinations, only: [:index, :edit, :create, :update, :destroy]

    get 'customers' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/information' => 'customers#update'
    patch 'customers/quit'

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :item_genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]do
      member do
        get 'order_index'
      end
    end
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :searchs, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  validates :name,          presence: true
  validates :postal_code,   presence: true, format: { with: /\A\d{7}\z/ }
  validates :address,       presence: true, format: { with: /\A[ぁ-んァ-ン[ ][　]一-龥々a-zA-Z]+\z/ }

  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, confirm_payment: 1, producting: 2, waiting_delivery: 3, start_delivery: 4 }

  def subtotal
    item.with_tax_price * count
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer_id
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
    if @order.update(order_params)
      @order_items.update_all(status: "waiting_product") if @order.status == "confirm_payment"
    end

    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status, :customer_id)
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row d-inline">
  <div class="offset-2 pl-3">
    <h5 class="bg-light col-4 text-center px-0"><%= @customer.full_name %>さんの注文履歴一覧</h3>
  </div>
  <div class="col-md-8 mx-auto">
    <table class="table table-hover border-bottom">
      <thead class="bg-light">
        <tr class="text-center">
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr class="text-center">
              <!--購入日時-->
            <td>
              <%= link_to admin_order_path(order) do %>
                <%= l order.created_at,format: :time %>
              <% end %>
            </td>
              <!--注文個数-->
            <td class="align-middle"><%= order.order_items.sum(:count) %></td>
              <!--注文ステータス-->
            <td class="align-middle"><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
      <div class="mx-auto">
        <%= paginate @orders, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h3 class="mt-3">注文履歴詳細</h3>
<div class="row">
  <div class="col-md-10">
    <table class="table table-borderless align-middle">
      <tr>
        <th class="col-md-2">購入者</th>
        <td>
          <%= link_to admin_customer_path(@customer) do %>
            <%= @order.name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= l @order.created_at %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %>
            <%= @order.address %><br>
            <%= @order.name %>
        </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_i18n %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with model:@order, url: admin_order_path do |f| %>
          <%= f.select :status, Order.statuses_i18n.invert %>
          <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

<div class="row position-relative mb-5">
  <div class="col-md-8">
    <table class="table">
      <thead class="bg-light">
        <tr class="align-middle">
          <th class="col-5">商品名</th>
          <th >単価</th>
          <th>数量</th>
          <th>小計</th>
          <th>制作ステータス</th>
          <th></th>
        </tr>
      </thead>
      <% @order.order_items.each do |order_item| %>
      <tbody class"d-flex justify-content-center">
        <tr class="text-center">
            <!--商品名-->
          <td class="align-middle text-left"><%= order_item.item.name %></td>
            <!--単価(税込み)-->
          <td class="align-middle">¥<%= order_item.price.to_s(:delimited) %></td>
            <!--数量-->
          <td class="align-middle"><%= order_item.count %></td>
            <!--小計-->
          <td class="align-middle">¥<%= (order_item.price * order_item.count).to_s(:delimited) %></td>
            <!--制作ステータス-->
            <%= form_with model:order_item, url: admin_order_item_path(order_item) do |f| %>
          <td class="align-middle"><%= f.select :status, OrderItem.statuses_i18n.invert, class: "form-control" %></td>
          <td class="align-middle"><%= f.submit "更新", class: "btn btn-success" %></td>
            <% end %>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>


  <div class="col-3 offset-1 pr-0 pt-5">
    <div class="">
      <table class="table table-borderless align-bottom">
          <tr>
            <th>商品合計</th>
            <td>¥<%= (@order.amount_billed - @order.delivery_fee).to_s(:delimited) %></td>
          </tr>
          <tr>
            <th>送料</th>
            <td>¥<%= @order.delivery_fee %></td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td>¥<%= @order.amount_billed.to_s(:delimited) %></td>
          </tr>
      </table>
    </div>
  </div>
</div>