config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show] do
      collection do
          get '/search' => 'items#search'
      end
    end
    resources :item_genres, only: [:show]

    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :destinations, only: [:index, :edit, :create, :update, :destroy]

    get 'customers' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/information' => 'customers#update'
    patch 'customers/quit'

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :item_genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]do
      member do
        get 'order_index'
      end
    end
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :searchs, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :count, numericality: { greter_than: 0, less_than: 11 }

  def subtotal
    item.with_tax_price * count
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :destinations

  validates :last_name,       presence: true
  validates :last_name_kana,  presence: true
  validates :first_name,      presence: true
  validates :first_name_kana, presence: true
  validates :email,           presence: true, uniqueness: true
  validates :postal_code,     presence: true, format: { with: /\A\d{7}\z/, allow_blank: true}
  validates :address,         presence: true
  validates :phone_number,    presence: true, format: { with: /\A0\d{9,10}\z/, allow_blank: true}

  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["last_name","first_name", "phone_number"]
  end

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address,     presence: true, format: { with: /\A[ぁ-んァ-ン[ ][　]一-龥々a-zA-Z]+\z/ }
  validates :name,        presence: true, format: { with: /\A[ぁ-んァ-ン一-龥a-zA-Z]+\z/ }

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  belongs_to :item_genre, foreign_key: 'genre_id'
  has_many :cart_items
  has_many :order_items

  validates :name, presence: true
  validates :introduction, presence: true
  validates :item_image, presence: true
  validates :price, presence: true,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 }


  scope :recentry_items, -> { order(created_at: :desc).limit(4)}

  def get_item_image(width, height)
    item_image.variant(resize_to_fill: [width, height]).processed
  end


  def status
    if is_availabled? == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name","introduction"]
  end

end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  has_many :items, foreign_key: "genre_id"

  validates :name, presence: true,  confirmation: { type: :name, message: :blank }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  validates :name,          presence: true
  validates :postal_code,   presence: true, format: { with: /\A\d{7}\z/ }
  validates :address,       presence: true, format: { with: /\A[ぁ-んァ-ン[ ][　]一-龥々a-zA-Z]+\z/ }

  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, confirm_payment: 1, producting: 2, waiting_delivery: 3, start_delivery: 4 }

  def subtotal
    item.with_tax_price * count
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum status: { do_not_start: 0, waiting_product: 1, producting: 2, completed_product: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    # 注文履歴一覧　1ページ当たりの表示数は10
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @genres = ItemGenre.pluck(:name, :id)
    @item = Item.new
  end

  def create
    @genres = ItemGenre.pluck(:name, :id)
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @genres = ItemGenre.pluck(:name, :id)
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.page(params[:page]).per(10)
    
  end

  def edit
    @genres = ItemGenre.pluck(:name, :id)
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else 
      @genres = ItemGenre.pluck(:name, :id)
      render 'edit'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_availabled, :item_image)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search_q

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :last_name_kana, :first_name, :first_name_kana, :address, :postal_code, :phone_number, :is_deleted])
  end

  def search_q
    unless admin_signed_in?
      @q = Item.ransack(params[:q])
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_genres_helper.rb
module Admin::ItemGenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def embedded_svg(filename, options={})
    file = File.read(Rails.root.join('app', 'assets', 'images', 'svg', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end

end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom mx-auto">
  <div class='container mt-3'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="text-light">ながのCAKE.©</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container header-nav-box">
      <%= link_to root_path do %>
        <div class="svg_wrapper">
          <%= embedded_svg('nagano_nav.svg', class: 'nagano_svg') %>
        </div>
      <% end %>
      <div>
        <ul class="ml-auto mb-0">
          <div class="navbar-nav ml-auto">
            <div class="d-flex align-items-center">
              <% if customer_signed_in? %>
                <p class="mb-0 text-light font-weight-bold">ようこそ、<%= current_customer.last_name %>さん！</p>
              <% end %>
            </div>
            <div>
              <div class="navbar-nav">
                <% if admin_signed_in? %>
                  <li><%= link_to "商品一覧", admin_items_path, class: 'btn navbar-btn btn-outline-light' %></li>
                  <li><%= link_to "会員一覧", admin_customers_path, class: 'btn navbar-btn btn-outline-light ml-3'%></li>
                  <li><%= link_to "注文履歴一覧", admin_path, class: 'btn navbar-btn btn-outline-light ml-3'%></li>
                  <li><%= link_to "ジャンル一覧", admin_item_genres_path, class: 'btn navbar-btn btn-outline-light ml-3'%></li>
                  <li>
                    <%= link_to destroy_admin_session_path, method: :delete, class: 'btn navbar-btn btn-outline-light ml-3' do %>
                      ログアウト
                    <% end %>
                  </li>
                <% elsif customer_signed_in? %>
                  <li><%= link_to "マイページ", customers_path, class: 'btn navbar-btn btn-outline-light ml-5' %></li>
                  <li><%= link_to "商品一覧", items_path, class: 'btn navbar-btn btn-outline-light ml-3' %></li>
                  <li><%= link_to "カート", cart_items_path, class: 'btn navbar-btn btn-outline-light ml-3' %></li>
                  <li>
                    <%= link_to destroy_customer_session_path, method: :delete, class: 'btn navbar-btn btn-outline-light ml-3' do %>
                      ログアウト
                    <% end %>
                  </li>
                <% else %>
                  <li><%= link_to "About", about_path, class: 'btn navbar-btn btn-outline-light' %></li>
                  <li><%= link_to "商品一覧", items_path, class: 'btn navbar-btn btn-outline-light ml-3' %></li>
                  <li><%= link_to "新規登録",new_customer_registration_path , class: 'btn navbar-btn btn-outline-light ml-3' %></li>
                  <li><%= link_to "ログイン", new_customer_session_path , class: 'btn navbar-btn btn-outline-light ml-3' %></li>
                <% end %>
              </div>
              <div class="float-right mt-2">
                <% if admin_signed_in? %>
                  <%= render 'admin/searchs/search_form' %>
                <% else %>
                  <%= render 'public/items/search_form', q: @q %>
                <% end %>
              </div>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6bb66a36c5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-preview"></meta>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="ml-5 mt-3 text-info">
        <p id="notice"><%= notice %></p>
      </div>
      <div class="ml-5 mt-3 text-danger">
        <p class="alert"><%= alert %></p>
      </div>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>